import './globals.css'

import { Container, SSRProvider } from '@/app/components/bootstrap';

import { Exo_2 } from 'next/font/google'
import NavBar from './NavBar'

const exo = Exo_2({ subsets: ['latin'], weight: ['500'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <body className={exo.className}>
        <SSRProvider>
        <NavBar /> 
          <main>
            <Container> 
                {children}
              </Container>
          </main>
        </SSRProvider>
      </body>
    </html>
  )
}
