import './globals.css'

import ApplyCustomFont from './clientFont';
import { Container } from '@/app/components/bootstrap';
import Head from 'next/head';
import ModeToggle from '@/www/registry/default/example/mode-toggle';
import NavBar from './NavBar'
import { ThemeProvider } from './components/theme-provider';
import css from 'styled-jsx/css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <html lang="en">
       <body>
        <ApplyCustomFont />
        {/* <NavBar />  */}
          <main>
            <ThemeProvider
             attribute="class"
             defaultTheme="system"
             enableSystem
             disableTransitionOnChange
           >
              <Container> 
                <ModeToggle />
                
                {children}
              </Container>
            </ThemeProvider>
          </main>
      </body>
    </html>
    </>
  );
}
