import './globals.css'

import ApplyCustomFont from './clientFont';
import { Container } from '@/app/components/bootstrap';
// import DarkModeToggle from '../components/ui/dark-mode-toggle';
import Head from 'next/head';
import ModeToggle from '@/www/registry/default/example/mode-toggle';
import NavBar from './NavBar'
import { ThemeProvider } from '../components/ui/theme-provider';
import WalletButton from './connectWallet';
import css from 'styled-jsx/css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <html lang="en">
       <body>
        <ApplyCustomFont />
        {/* <NavBar />  */}
          <main>
            <ThemeProvider
             attribute="class"
             defaultTheme="dark"
             enableSystem
             disableTransitionOnChange
           >
              {/* <Container>  */}
                <ModeToggle />
                  <WalletButton chains={[]} wagmiConfig={undefined} />
                {children}
             {/* ` </Container>` */}
            </ThemeProvider>
          </main>
      </body>
    </html>
    </>
  );
}
